[build]
  builder = "@angular-devkit/build-angular:application"

[serve]
  builder = "@angular-devkit/build-angular:dev-server"

[test]
  builder = "@angular-devkit/build-angular:karma"

[lint]
  builder = "@angular-eslint/builder:lint"
