// <auto-generated />
using ClauseLens.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClauseLens.Infrastructure.Migrations
{
    [DbContext(typeof(ClauseLensDbContext))]
    [Migration("20260701000000_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // The model snapshot is intentionally minimal — EF Core will
            // regenerate the full snapshot on the first real `dotnet ef
            // migrations add` invocation against a live database. The C#
            // migration body is the source of truth for this initial
            // bootstrap; the snapshot is present only to satisfy the
            // design-time tooling contract.
        }
    }
}
