// <auto-generated />
namespace ClauseLens.Infrastructure.Migrations
{
    [DbContext(typeof(Persistence.ClauseLensDbContext))]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // See Designer.cs for the snapshot stub. EF will regenerate
            // this on the first real `dotnet ef migrations add` against a
            // live database.
        }
    }
}
